env:
    CIRRUS_CLONE_DEPTH: 1
    CIRRUS_WORKING_DIR: "/tmp"
    
task:
  name: "Kernel deploy.."
  timeout_in: 2h
  container:
      image: anggit86/dev:latest
      cpu: 8
      memory: 32G
        
  Build-Env-Setup_background_script:
       - ./eleven/env.sh

  Storage-Checker_background_script:
      - df -h
      - lsblk
      - ls -l -a -h
  
  Sync_script:
      - ./eleven/download.sh

  Build_kernel_GCC_script:
      - ./eleven/gcc.sh

  Remove_old_build_script:
      - ./eleven/rm.sh

  Build_kernel_Clang_script:
      - ./eleven/clang.sh
      
  Update_ccache_script:
      - ./eleven/done.sh
