env:
    DEVICE_CODENAME: rosy
    BUILD_USER: rosy
    BUILD_HOST: anggit86
    TG_TOKEN: nfs-project
    TG_CHAT_ID: "ENCRYPTED[52ef97ea6128737b88337a868fbf49e705bfa470759ef47d62f119c39dd53ce152192bbddfbf8ff216ce3c1e3a824042]"
    RCLONECONFIG: "ENCRYPTED[bece68fe5c12aa3c8c4f1947d259441433792dedd28f06e03fada62cbb940b34662858cee1a0aded71a858742a17978f]"
    
task:
  name: "Kernel deploy.."
  timeout_in: 2h
  container:
      image: anggit86/dev:latest
      cpu: 8
      memory: 32G
        
  Build-Env-Setup_background_script:
       - ./eleven/env.sh

  Storage-Checker_background_script:
      - df -h
      - lsblk
      - ls -l -a -h
  
  Sync_script:
      - ./eleven/download.sh

  Build_kernel_GCC_script:
      - ./eleven/gcc.sh

  Remove_old_build_script:
      - ./eleven/rm.sh

  Build_kernel_Clang_script:
      - ./eleven/clang.sh
      
  Update_ccache_script:
      - ./eleven/done.sh
