env:
    DEVICE_CODENAME: whyred
    BUILD_USER: xiaomi
    BUILD_HOST: whyred
    KERNEL_SOURCE: https://github.com/IQ-7/kernel_xiaomi_whyred
    KERNEL_BRANCH: 12
    TOOLCHAIN_SOURCE: https://pf.osdn.net/gitroot/n/nf/nfs86/NFS-clang.git
    TOOLCHAIN_BRANCH: master
    CIRRUS_CLONE_DEPTH: 1
    CIRRUS_WORKING_DIR: /tmp/cirrus-ci-build
    ANYKERNEL: "https://github.com/NFS-Project/AnyKernel3.git"
    TG_TOKEN: "ENCRYPTED[4548ed54125ed96f671e9293f5dae83eb2ff9bd7f830a3669a230c3b520251c2db68741624a40873eaf04c7b833f98c6]"
    TG_CHAT_ID: "ENCRYPTED[e209410340316d4a43d7428f1b6950c7f8261333ee89ca0f6091893fd874f9704ad6b6cb7cb67b0176dc3bbb883d027f]"

task:
  name: "Kernel Build.."
  timeout_in: 1h
  container:
      image: anggit86/docker:cirrus
      cpu: 8
      memory: 32G

  Sync_script:
      - ./download.sh

  Build_kernel_Clang_script:
      - ./clang.sh
      - ./done.sh
